// English version of the seed questions. EN_ITEMS[i] = [question, hint, draft] for id "q" + (i + 1).
// Text in [Needs input: ...] marks a gap you should fill with a real example.
(function () {
  window.CATEGORY_EN = {
    "A. Giới thiệu và động lực": "A. Introduction and motivation",
    "B. Product Owner và Agile": "B. Product Owner and Agile",
    "C. Requirement gathering và stakeholder": "C. Requirement gathering and stakeholders",
    "D. Đối tác bên ngoài và tích hợp": "D. External partners and integration",
    "E. Lending domain": "E. Lending domain",
    "F. Risk và Compliance": "F. Risk and Compliance",
    "G. Data-driven": "G. Data-driven",
    "H. Tình huống và behavioral": "H. Situational and behavioral",
    "I. Câu hỏi hỏi lại phỏng vấn viên": "I. Questions to ask the interviewer",
    "J. Giới thiệu sản phẩm VNShop & USP (Product Sense)": "J. VNShop product intro and USP (Product Sense)",
    "K. Cơ cấu team & cách PO vận hành (Execution)": "K. Team structure and how the PO operates (Execution)",
  };

  const EN_ITEMS = [
    // ---- A
    ["Introduce yourself and your path from System Analyst to PO",
      "TOSY (D365 F&O, Power Platform), then VNPAY (VNShop BO, VNTIX, hotel/ticketing)",
      "I have over 3 years of experience as a BA/PO. I'm currently the PO for the VNShop Back Office at VNPAY, a self-built ERP-style system for orders, inventory and suppliers. Before that I was a System Analyst at TOSY, configuring Dynamics 365 F&O and building Power Apps, Power Automate and Power BI. That made me comfortable bridging business and technology, and I want to apply it to lending products."],
    ["Why do you want to move into lending (cash loan, BNPL)?",
      "Link to fintech/payments at VNPAY",
      "[Needs input: your real reason.] Frame: at VNPAY I build fintech products from market research to go-live; I want to work on products with credit risk and compliance requirements, where product, risk, legal and data have to decide together."],
    ["Why are you leaving VNPAY, or what are you looking for in this role?",
      "The JD matches your multi-party coordination and partner integration skills",
      "[Needs input: your real reason.] Aim for: looking for a lending product and an environment where Risk, Legal and Data work closely with product. Don't criticise your current employer."],
    ["What achievement are you most proud of?",
      "Auto-assign carrier; Open API for suppliers; AI-augmented BA workflow",
      "I built a rule-based flow that automatically assigns the carrier and value-added services per warehouse, taking thousands of orders a day from manual handling down to a few minutes. I also designed an Open API for suppliers (inventory sync, parcel status updates, carrier handover, cancel/return) to digitise the process. [Needs input: exact orders per day, if you're allowed to say.]"],
    ["What are your strengths and weaknesses?",
      "Strengths: documentation, multi-party coordination. Weakness: no direct lending experience",
      "Strengths: I turn business requirements into clear PRDs/BRDs/user stories and coordinate IT, operations and partners through to go-live. Weakness: I haven't worked directly on a lending product. I'm closing that gap by [Needs input: what you've studied or are studying, e.g. courses, SBV regulations] and by applying the approach I already use: survey, Fit-Gap, and alignment with stakeholders."],
    ["Where do you see yourself in 1-3 years in this role?",
      "Not in your CV",
      "[Needs input: your goals.] Frame: in year one, master the lending lifecycle and its metrics; after that, own a whole product line."],
    // ---- B
    ["How is your PO role different from a BA?",
      "You do both: survey, Fit-Gap, PRD/BRD writing, backlog prioritisation",
      "On VNShop BO I cover both sides. As a BA: surveys, confirming Fit-Gap with the client, writing PRDs/BRDs. As a PO: prioritising the backlog, assigning work to IT, operations and partners, and keeping delivery on track to go-live. A BA clarifies and specifies requirements; a PO is accountable for scope, priority and product outcomes."],
    ["What criteria do you use to prioritise the backlog?",
      "\"Business impact and urgency\", tied to the go-live deadline",
      "I rank the backlog by business impact and urgency, check it against the go-live deadline, then assign work to IT, operations and partners. [Needs input: a concrete example of cutting or postponing an item.]"],
    ["Describe the Scrum/Agile process you run",
      "Your CV says Agile/Scrum",
      "[Needs input: sprint length, ceremonies (planning, review, retro), Definition of Done, who takes part.] Only describe what your team actually runs. The JD asks for experience running an Agile team as PO, so prepare this one carefully."],
    ["How do you write user stories and acceptance criteria? Give an example",
      "PRD/BRD/user stories on VNShop BO",
      "I turn confirmed requirements and the Fit-Gap results into a PRD/BRD and user stories, then present them to stakeholders and developers to agree on scope before we build. [Needs input: a sample user story with acceptance criteria from VNShop BO.]"],
    ["What do you do when developers say they can't make the deadline?",
      "Split tasks along the go-live timeline, order by impact",
      "I break the remaining work into tasks along the go-live timeline, re-order them by business impact and urgency, propose solutions that fit the existing system constraints, and agree any scope change with stakeholders first. [Needs input: a real example.]"],
    ["How do you handle a change request in the middle of a sprint?",
      "No example in your CV",
      "[Needs input: a real example.] Frame: assess the impact on scope and go-live, compare priority against the backlog, and get stakeholder confirmation before accepting the change."],
    ["How do you measure the success of a feature after go-live?",
      "Your CV mentions \"post-launch evaluation\"",
      "I run a post-go-live evaluation. For auto-assign carrier, the main measure was order processing time, from manual handling down to a few minutes. [Needs input: the metrics you actually track afterwards.]"],
    ["How do you use Jira and Confluence?",
      "Jira and Confluence are listed under Tools",
      "[Needs input: how you really use them, e.g. Jira for backlog, epics and tasks; Confluence for PRDs.]"],
    ["What is an MVP? How do you define one?",
      "No example in your CV",
      "[Needs input: an MVP example from a VNShop feature.] Frame: pick the smallest piece that solves the core operational problem within system constraints, then expand after go-live."],
    ["How do you manage technical debt and existing system constraints?",
      "\"Propose solutions that fit within existing system constraints\"",
      "I analyse the current state of the platform to find operational problems, propose solutions that fit its constraints, and split the work into tasks along the go-live timeline. [Needs input: a real constraint and how you handled it.]"],
    // ---- C
    ["How do you gather and validate requirements from senior management?",
      "Stakeholder survey, requirement-validation session",
      "I run stakeholder surveys and requirement-validation sessions with the client team to lock scope, confirm the Fit-Gap between business needs and platform capability, propose solutions and get approval from all stakeholders. [Needs input: an example of working with management.]"],
    ["What is Fit-Gap? How do you do it?",
      "Fit-Gap between business needs and platform capability; D365 F&O experience at TOSY",
      "Fit-Gap compares business needs against what the platform already supports, to show what fits and what is a gap, and then proposes how to handle each gap. On VNShop BO I confirm the result with stakeholders before writing the PRD/BRD. At TOSY I configured D365 F&O and used Power Platform for requirements outside the standard ERP."],
    ["When two stakeholders have conflicting requirements, what do you do?",
      "\"Get approval from all related stakeholders\"",
      "I use a validation session to clarify system constraints and the impact of each option, and I only close the decision once all related stakeholders approve. [Needs input: a real example.]"],
    ["Tell me about a time you had to refuse or push back on a stakeholder's request",
      "No example in your CV",
      "[Needs input: a real example.] Frame: state the constraint and the impact in terms of business impact and urgency, and offer an alternative within system limits."],
    ["What do you do with a vague requirement from the business?",
      "Survey, analyse current state, propose a solution",
      "I survey and clarify with stakeholders, analyse the platform's current state to diagnose the problem, propose a solution, then confirm it again before writing the PRD. [Needs input: a real example.]"],
    ["How do you work with internal customers versus external partners?",
      "Client team (VNShop), suppliers, carrier partners, internal IT",
      "With the client team I survey and lock scope through Fit-Gap. With partners (suppliers, carriers) I work through the Open API and guidance documents. With IT I work through the PRD and the backlog."],
    ["How do you present a PRD to stakeholders and developers?",
      "Present to align scope and execution",
      "I present the PRD/BRD and user stories to stakeholders and the dev team to agree on scope and approach before implementation. [Needs input: how you tailor the content for each audience.]"],
    ["How do you do market research and competitor benchmarking?",
      "CV skills: competitor benchmarking, market trends, feature/UX gaps",
      "[Needs input: a concrete example, e.g. hotel booking or ticketing.] The JD also asks for market analysis for cash loan and BNPL, so prepare how you would research this space."],
    ["How do you train operations and frontline staff when you release a new feature?",
      "Documentation and training for operations, warehouse and suppliers",
      "For every new feature I write documentation and run internal training for operations, warehouse and suppliers so frontline staff understand the product before they use it. [Needs input: one specific feature and the feedback you got.]"],
    // ---- D
    ["Tell me about a project where you co-developed or integrated with a partner",
      "Open API for suppliers: inventory sync, parcel status, carrier handover, cancel/return",
      "I designed an Open API for suppliers covering inventory sync, parcel status updates, carrier handover and cancel/return, to digitise operations and reduce reliance on manual work. [Needs input: the partner's role in co-development, who did what, the result.]"],
    ["How do you design an API spec for partners?",
      "Open API specification",
      "I wrote the API specification for the four business areas above. [Needs input from your Open API document: authentication mechanism, webhook vs polling, error handling.]"],
    ["What do you do when a partner misses the timeline or the spec?",
      "No example in your CV",
      "[Needs input: a real example.] Frame: find out the cause, split the scope along the go-live timeline, and agree the approach with stakeholders."],
    ["How do you onboard a new partner?",
      "Documentation and training for the supplier team",
      "I build documentation and training for the supplier team when a new feature ships. [Needs input: your steps for onboarding a supplier onto the Open API, e.g. sandbox environment, checklist.]"],
    ["How do you handle errors and data synchronisation between two systems?",
      "Inventory sync, parcel status; TOSY: data integrity, migration, Tier 3",
      "My Open API covers inventory sync and parcel status updates. At TOSY I was responsible for data integrity and system migration, and worked with Microsoft Support (Lifecycle Services) on Tier 3 production incidents. [Needs input: how you detect and resolve discrepancies between the two systems.]"],
    // ---- E
    ["Distinguish cash loan, personal loan, installment loan, line of credit and BNPL",
      "Say clearly that you are still learning this area",
      "Cash loan/personal loan: a one-off loan with a fixed amount and term, repaid periodically. Installment loan: repayment on a fixed schedule, usually tied to a specific purpose. Line of credit: a revolving limit you can draw and repay repeatedly, with interest charged on the outstanding balance. BNPL: buy now, pay later at the point of sale, short tenor, small limit."],
    ["Describe the loan origination flow from application to disbursement",
      "Not in your CV",
      "Collect customer information, verify identity, assess and score credit, decide approval and limit, sign the contract, disburse. [Needs input: which step is where this company's product differs, once you've researched it.]"],
    ["What is underwriting? What data is used for scoring?",
      "Not in your CV",
      "Underwriting is assessing the ability and willingness to repay in order to decide approval, limit and interest rate. Typical data: customer-declared information, income, credit history (e.g. from CIC), behavioural and transaction data."],
    ["What does the loan servicing lifecycle include?",
      "Not in your CV",
      "Payment reminders, recording payments, handling late payments, collection, settlement or early repayment, customer support and reporting."],
    ["Lending product metrics: approval rate, NPL, DPD, vintage, roll rate",
      "Not in your CV",
      "Approval rate: share of applications approved. DPD: days past due. NPL: non-performing loan ratio. Roll rate: share of loans moving into a worse delinquency bucket. Vintage: portfolio quality by disbursement month. Add conversion and collection rate."],
    ["How does BNPL differ from cash lending in risk and revenue model?",
      "Not in your CV",
      "BNPL is tied to a purchase at a merchant, with small limits, short tenor and an instant decision at checkout. Cash lending disburses money to the customer, with larger limits and terms, so risk and collection costs differ. BNPL revenue usually includes merchant fees; cash lending earns mainly from interest and fees. [Needs input: verify against the interviewing company's model.]"],
    ["How would you design a new BNPL product from scratch?",
      "Reuse the process you know: survey, Fit-Gap, partners, measurement",
      "I'd start with a needs survey and market analysis, confirm Fit-Gap against the existing platform, pick a small MVP, co-design the partner integration as I did with the Open API, work with Risk, Legal and Compliance on approval conditions and compliance, then set up a tracking dashboard with Data."],
    ["What do you know about lending and consumer finance regulation in Vietnam?",
      "Not in your CV",
      "[Needs input: research this yourself and only cite documents you've read.] Topics to look up: consumer lending, debt classification and provisioning, personal data protection, electronic customer verification (eKYC). If unsure, say you're still learning and would confirm with Legal and Compliance."],
    ["What do you know about fintech and lending in Vietnam?",
      "Not in your CV",
      "[Needs input: research the interviewing company and its competitors; name 2-3 products you've tried and compare them.]"],
    ["What experience do you have with banks or financial institutions?",
      "Only VNPAY (payments) and AP/AR at TOSY",
      "I haven't worked at a bank or lender. I have fintech product experience at VNPAY and digitised financial processes (AP/AR) on D365 F&O at TOSY."],
    // ---- F
    ["How do you work with Risk, Legal and Compliance when launching a product?",
      "No direct example in your CV yet",
      "[Needs input: a real example, e.g. a policy, permissions or approval workflow at VNShop or VNPAY.] If you don't have one, say so plainly and describe the approach you use: confirm requirements and get approval from all stakeholders."],
    ["When a business requirement conflicts with compliance, how do you handle it?",
      "Align and get approval from all stakeholders",
      "I bring both sides into one validation session, clarify the constraints and impact, propose options that meet compliance requirements first, and only close the decision when stakeholders agree. [Needs input: a real example, if any.]"],
    ["How do you ensure data integrity and an audit trail?",
      "TOSY: data integrity, migration; Tier 3 with Microsoft Support",
      "At TOSY I was responsible for enterprise data integrity and system migration, and handled Tier 3 production incidents with Microsoft Support. [Needs input: how you specifically ensured an audit trail, if you did.]"],
    ["How do you balance growth (approval rate) against risk control?",
      "Not in your CV",
      "[Needs input: your own view.] Frame: approving more raises revenue but can raise bad debt, so the PO works with Risk and Data to set thresholds, tracks both approval rate and portfolio quality (NPL, DPD), and adjusts gradually."],
    ["How do you handle product policies and processes?",
      "\"Product policies/processes\" under Skills",
      "I define product policies and processes, then put them into the PRD/BRD and the operations training. [Needs input: one specific policy you wrote.]"],
    // ---- G
    ["How do you work with Data Analysts to build dashboards?",
      "Real-time Power BI dashboard for management (TOSY)",
      "At TOSY I built automated Power BI dashboards so management could see operational figures in real time. [Needs input: how you work with DAs at VNPAY, e.g. defining metrics and reporting requirements.]"],
    ["How do you use data to spot problems and customer needs?",
      "Platform current-state analysis, diagnosing operational problems",
      "I analyse the platform's current state to diagnose operational problems and then propose solutions; at TOSY I had Power BI dashboards for management. [Needs input: one example going from data to insight to decision.]"],
    ["Do you use SQL? At what level?",
      "CV lists Power BI; no SQL, Tableau or Excel",
      "[Needs input: answer truthfully.] The JD lists SQL and Tableau as a plus, not a requirement. If you haven't used them in practice, say so directly, give a concrete learning plan, and point to your Power BI work."],
    ["Which KPIs would you track for a lending product?",
      "Not in your CV",
      "[Needs input: pick 3-5 KPIs and explain why.] Suggestions: conversion, approval rate, disbursement rate, DPD, NPL, collection rate."],
    ["Tell me about a product decision you made using data",
      "Auto-assign carrier (thousands of orders a day, a few minutes)",
      "You can use the auto-assign carrier flow: thousands of orders a day, from manual handling down to a few minutes. [Needs input: the data you used to decide, and the before/after numbers.]"],
    ["How do you design an A/B test or evaluate effectiveness?",
      "Not in your CV",
      "[Needs input: a real example.] If you have none, explain how you would evaluate: set the metric and a before/after baseline, and track it together with the DA."],
    // ---- H
    ["Tell me about your hardest project and how you got through it",
      "Open API or auto-assign carrier",
      "Pick one. Open API: I designed the spec for four flows (inventory, parcel status, carrier handover, cancel/return). Auto-assign: warehouse-based rules, thousands of orders from manual to a few minutes. [Needs input, in STAR format: the specific difficulty, your actions, the result.]"],
    ["Tell me about a wrong decision and what you learned",
      "Not in your CV",
      "[Needs input: a real example.] Choose a genuine mistake, state the consequence and what you changed afterwards."],
    ["What do you do when something goes wrong at go-live?",
      "Go-live coordination; Tier 3 at TOSY",
      "I coordinate IT, operations and partners through go-live; at TOSY I worked with Microsoft Support on Tier 3 production incidents. [Needs input: one specific incident and how you handled it.]"],
    ["How do you handle deadline pressure and many parallel tasks?",
      "Coordinating IT, operations, partners to go-live",
      "I rank the backlog by business impact and urgency and assign work to IT, operations and partners to keep delivery on track to go-live. [Needs input: a real example.]"],
    ["How quickly do you pick up a new domain?",
      "ERP to fintech; AI agents, Knowledge Graph, Power Platform",
      "I moved from ERP (D365 F&O, Power Platform) to fintech products, and built a Knowledge Graph and 2 AI agent skills for myself to learn and look up business rules faster. [Needs input: how you're learning lending specifically.]"],
    ["How do you use AI in your BA work?",
      "Knowledge Graph + 2 AI agent skills on Claude",
      "I built a Knowledge Graph for VnShop and D365 F&O, plus 2 AI agent skills on Claude, to look up business definitions and analyse impact when SRS/URD documents change. Impact analysis when preparing a PRD dropped from several hours to under 15 minutes, with less risk of missing a related module. Also prepare an answer on data security when using AI, because financial companies often ask about it."],
    ["Tell me about a time you convinced someone who disagreed",
      "Not in your CV",
      "[Needs input: a real example.] Frame: rely on data, impact and the confirmed Fit-Gap results."],
    ["What is your expected salary and notice period?",
      "Not in your CV",
      "[Needs input: your answer.]"],
    // ---- I
    ["What stage is the product this PO owns at (new, growth, optimisation)?",
      "Purpose: understand the scope",
      "Listen for: does the PO decide the roadmap or only execute it"],
    ["How many developers and DAs are on the team, and how does the PO work with Risk/Compliance?",
      "Purpose: structure and collaboration",
      "Listen for: is there a dedicated Risk team working with the PO, and how often"],
    ["Who are the main external partners (bank, credit bureau, merchant...)?",
      "Purpose: understand the model",
      "Listen for: how much integration work falls on the PO, to connect with your Open API experience"],
    ["Which metrics decide success in this role over the first 6-12 months?",
      "Purpose: expectations",
      "Listen for: concrete KPIs to compare with your capabilities"],
    ["What is the current roadmap and the product's biggest challenge?",
      "Purpose: context",
      "Listen for: the biggest risk and what you would have to deal with first"],
    ["What data stack does the company use (SQL, Tableau...)? Does the PO query data directly?",
      "Purpose: clarify the data gap",
      "Listen for: whether the PO must write SQL or only works with DAs, to size your gap"],
    ["Is there a lending domain training programme for newcomers?",
      "Purpose: deliberately close your gap",
      "Listen for: the level of support for people without lending experience"],
    ["How are decisions made between Product, Risk and Business?",
      "Purpose: collaboration culture",
      "Listen for: who has the final say in a conflict, and how fast approvals are"],
    ["Why is this position open?",
      "Purpose: hiring context",
      "Listen for: new headcount from expansion or a replacement, and why"],
    ["What are the next steps in the hiring process?",
      "Purpose: closing the interview",
      "Listen for: the number of remaining rounds and the timeline"],
    // ---- J
    ["Give an overview of the VNShop product you work on, as a PO",
      "VNShop is an e-commerce platform within the VNPAY app/e-wallet ecosystem; you own the Back Office for orders, inventory and suppliers",
      "VNShop is an e-commerce product integrated into VNPAY's app/e-wallet ecosystem, letting users buy from many suppliers (NCCs) inside the app they already use to pay. I own the Back Office (BO): a self-built, ERP-style system that handles orders, inventory and supplier operations, helping the operations and warehouse teams process thousands of orders a day. [Needs input: current scale (number of suppliers, orders per month if allowed) to make the answer more concrete.]"],
    ["What is the product's Unique Selling Point?",
      "Not stated in your CV/records, so you need to confirm it",
      "[Needs input: your real USP from your own point of view.] Directions to check against: (1) buy right inside a payment app that already has a large user base, no extra app to install; (2) automated back-office operations (e.g. auto-assign carrier) that process orders faster than competitors; (3) built-in payment integration that reduces friction at checkout compared with a standalone marketplace. Pick the one USP that is really true; don't claim all three unless verified."],
    ["Who are the main users and what problem do they use the product to solve?",
      "BO serves operations/warehouse/suppliers; buyers use it via the VNPAY app",
      "There are two user groups: buyers shopping through the VNPAY app, and the operations/warehouse/supplier teams who use the Back Office to process orders, inventory and delivery. I focus on the second group: less manual work and fewer errors as orders grow quickly."],
    ["Why do customers choose VNShop over other channels?",
      "Not in your CV",
      "[Needs input: your real answer, ideally backed by data or customer feedback.] If you have no data, answer as a hypothesis and say clearly that it hasn't been validated with data, to avoid being challenged."],
    // ---- K
    ["Describe the structure of the team you work with (dev, DA, QA, design...)",
      "Headcount not specified in your CV",
      "[Needs input: number of devs/QA/DAs, who you report to.] Frame: name the roles (IT, operations, warehouse, suppliers, partners) and describe the PO as the coordinator between them through go-live, as your CV does."],
    ["How is the PO team organised and run (who do you report to, who do you work with daily)?",
      "Coordinating IT, operations, partners to go-live",
      "I am the bridge between the VNShop client team, IT, operations/warehouse and partners, keeping delivery on track to go-live. [Needs input: your direct manager and how often you meet each group.]"],
    ["What does a typical working day look like for you?",
      "Not in your CV",
      "[Needs input: describe it truthfully.] Use a real sequence: check backlog/tickets, work with stakeholders or devs, write documentation, follow up on go-live. Avoid generic lists."],
    ["How does an idea go from concept to go-live at VNShop, and who is involved at each step?",
      "Survey → Fit-Gap → PRD/BRD → backlog → implementation → training → post-go-live evaluation",
      "I start with a stakeholder survey and Fit-Gap confirmation, write the PRD/BRD and present it to stakeholders and developers, prioritise the backlog by impact/urgency, coordinate IT/operations/partners to go-live, then train operations and evaluate after launch. [Needs input: average time per step if asked in more depth.]"],
  ];

  window.SEED_EN = {};
  EN_ITEMS.forEach(([question, hint, draft], i) => { window.SEED_EN["q" + (i + 1)] = { question, hint, draft }; });
})();
