// Seed data: "Bộ câu hỏi phỏng vấn PO Lending (Cash loan / BNPL)" (Notion, 2026-09-28).
// Each entry: [question, hint, draft answer]. Ids are assigned from the position (q1..q77).
// Text in [Cần bổ sung: ...] marks a gap you should fill with a real example.
(function () {
  const groups = [
    ["A. Giới thiệu và động lực", [
      ["Giới thiệu bản thân và hành trình từ System Analyst sang PO",
        "TOSY (D365 F&O, Power Platform), sau đó VNPAY (VNShop BO, VNTIX, hotel/ticketing)",
        "Em có hơn 3 năm làm BA/PO. Hiện em là PO phụ trách Back Office VNShop tại VNPAY, một hệ thống kiểu ERP tự xây cho đơn hàng, tồn kho, nhà cung cấp. Trước đó em là System Analyst tại TOSY, cấu hình Dynamics 365 F&O và xây Power Apps, Power Automate, Power BI. Nhờ vậy em quen làm cầu nối giữa business và kỹ thuật, và muốn áp dụng điều đó vào sản phẩm cho vay."],
      ["Vì sao bạn muốn chuyển sang mảng lending (cash loan, BNPL)?",
        "Nối fintech/payment ở VNPAY",
        "[Cần bổ sung: lý do thật của bạn.] Khung: ở VNPAY em làm sản phẩm fintech từ nghiên cứu thị trường đến go-live; em muốn làm sản phẩm có rủi ro tín dụng và yêu cầu tuân thủ, nơi sản phẩm, rủi ro, pháp chế và dữ liệu phải cùng quyết định."],
      ["Vì sao bạn rời VNPAY, hay bạn tìm kiếm điều gì ở vị trí này?",
        "JD khớp năng lực phối hợp đa bên và tích hợp đối tác",
        "[Cần bổ sung: lý do thật.] Nên nói theo hướng tìm sản phẩm lending và môi trường có Risk, Legal, Data làm việc sát, không nói xấu nơi cũ."],
      ["Thành tựu tự hào nhất của bạn là gì?",
        "Auto-assign carrier; Open API cho NCC; AI-augmented BA workflow",
        "Em xây luồng tự động gán đơn vị vận chuyển và dịch vụ giá trị gia tăng theo kho bằng rule, giúp xử lý hàng nghìn đơn mỗi ngày từ thủ công xuống còn vài phút. Em cũng thiết kế Open API cho nhà cung cấp (đồng bộ tồn kho, cập nhật trạng thái kiện, bàn giao vận chuyển, huỷ/hoàn) để số hoá quy trình. [Cần bổ sung: số đơn/ngày cụ thể nếu được phép nói.]"],
      ["Điểm mạnh và điểm yếu của bạn?",
        "Mạnh: viết tài liệu, phối hợp đa bên. Yếu: chưa làm lending trực tiếp",
        "Mạnh: em biến yêu cầu business thành PRD/BRD/User Story rõ ràng và điều phối IT, vận hành, đối tác đến go-live. Yếu: em chưa làm trực tiếp sản phẩm cho vay. Em đang bù bằng [Cần bổ sung: việc bạn đã và đang học, ví dụ khoá học, quy định NHNN] và áp dụng cách làm em đã dùng: khảo sát, Fit-Gap, xác nhận với các bên liên quan."],
      ["Bạn hình dung 1-3 năm tới ở vai trò này thế nào?",
        "Không có trong CV",
        "[Cần bổ sung: mục tiêu của bạn.] Khung: năm đầu nắm vòng đời cho vay và các chỉ số; sau đó phụ trách trọn một dòng sản phẩm."],
    ]],
    ["B. Product Owner và Agile", [
      ["Vai trò PO của bạn khác BA thế nào?",
        "Bạn làm cả hai: khảo sát, Fit-Gap, viết PRD/BRD, ưu tiên backlog",
        "Ở VNShop BO em làm cả hai phía. Góc BA: khảo sát, xác nhận Fit-Gap với client, viết PRD/BRD. Góc PO: ưu tiên backlog, phân việc cho IT, vận hành, đối tác và giữ tiến độ đến go-live. BA làm rõ và đặc tả yêu cầu; PO chịu trách nhiệm phạm vi, thứ tự ưu tiên và kết quả sản phẩm."],
      ["Bạn ưu tiên backlog dựa trên tiêu chí nào?",
        "\"Business impact và urgency\", gắn deadline go-live",
        "Em xếp backlog theo mức ảnh hưởng đến business và độ khẩn cấp, đối chiếu với deadline go-live, rồi giao việc cho IT, vận hành và đối tác. [Cần bổ sung: một ví dụ cụ thể khi bạn phải cắt hoặc lùi một hạng mục.]"],
      ["Mô tả quy trình Scrum/Agile bạn đang chạy",
        "CV ghi Agile/Scrum",
        "[Cần bổ sung: độ dài sprint, các buổi họp (planning, review, retro), Definition of Done, ai tham gia.] Chỉ nói đúng những gì team bạn thực sự chạy. JD yêu cầu kinh nghiệm chạy team Agile với vai trò PO, nên đây là câu nên chuẩn bị kỹ."],
      ["Bạn viết User Story và Acceptance Criteria thế nào? Cho ví dụ",
        "PRD/BRD/User Story ở VNShop BO",
        "Em chuyển yêu cầu đã chốt và kết quả Fit-Gap thành PRD/BRD và User Story, trình bày cho stakeholder và dev để thống nhất phạm vi trước khi làm. [Cần bổ sung: một User Story mẫu kèm Acceptance Criteria từ VNShop BO.]"],
      ["Khi dev nói không kịp deadline, bạn làm gì?",
        "Chia task theo timeline go-live, xếp theo impact",
        "Em chia phần việc còn lại thành task theo timeline go-live, xếp lại theo business impact và urgency, đề xuất giải pháp nằm trong ràng buộc hệ thống hiện tại, và thống nhất với các bên liên quan trước khi đổi phạm vi. [Cần bổ sung: ví dụ thật.]"],
      ["Bạn xử lý yêu cầu thay đổi giữa sprint thế nào?",
        "Không có ví dụ trong CV",
        "[Cần bổ sung: ví dụ thật.] Khung: đánh giá tác động lên phạm vi và go-live, đối chiếu ưu tiên với backlog, xin xác nhận của các bên liên quan trước khi nhận thay đổi."],
      ["Bạn đo thành công của một feature sau go-live ra sao?",
        "CV có \"post-launch evaluation\"",
        "Em có bước đánh giá sau go-live. Với auto-assign carrier, thước đo chính là thời gian xử lý đơn, từ thủ công xuống còn vài phút. [Cần bổ sung: các metric bạn thực sự theo dõi sau đó.]"],
      ["Bạn dùng Jira và Confluence như thế nào?",
        "Jira, Confluence trong mục Tools",
        "[Cần bổ sung: cách dùng thật, ví dụ Jira quản lý backlog, epic, task; Confluence lưu PRD.]"],
      ["MVP là gì? Bạn xác định MVP thế nào?",
        "Không có ví dụ trong CV",
        "[Cần bổ sung: ví dụ MVP từ một feature VNShop.] Khung: chọn phần nhỏ nhất giải quyết vấn đề vận hành chính, phù hợp ràng buộc hệ thống, rồi mở rộng sau go-live."],
      ["Bạn quản lý technical debt và ràng buộc hệ thống hiện tại thế nào?",
        "\"Propose solutions that fit within existing system constraints\"",
        "Em phân tích hiện trạng nền tảng để tìm vấn đề vận hành, đề xuất giải pháp phù hợp ràng buộc hệ thống, và chia thành task theo timeline go-live. [Cần bổ sung: một ràng buộc thật và cách bạn xử lý.]"],
    ]],
    ["C. Requirement gathering và stakeholder", [
      ["Bạn thu thập và xác nhận yêu cầu từ senior management ra sao?",
        "Stakeholder survey, requirement-validation session",
        "Em chạy khảo sát stakeholder và các buổi xác nhận yêu cầu với đội client để chốt phạm vi, xác nhận Fit-Gap giữa nhu cầu business và năng lực nền tảng, đề xuất giải pháp và xin chấp thuận của tất cả bên liên quan. [Cần bổ sung: ví dụ làm việc với cấp quản lý.]"],
      ["Fit-Gap là gì? Bạn làm thế nào?",
        "Fit-Gap giữa nhu cầu business và năng lực nền tảng; kinh nghiệm D365 F&O ở TOSY",
        "Fit-Gap là đối chiếu nhu cầu business với năng lực sẵn có của nền tảng để chỉ ra phần đáp ứng được (fit) và phần còn thiếu (gap), rồi đề xuất cách xử lý gap. Ở VNShop BO em xác nhận kết quả này với các bên liên quan trước khi viết PRD/BRD. Ở TOSY em cấu hình D365 F&O và dùng Power Platform cho những yêu cầu nằm ngoài phần chuẩn của ERP."],
      ["Khi hai stakeholder xung đột yêu cầu, bạn xử lý thế nào?",
        "\"Get approval from all related stakeholders\"",
        "Em dùng buổi xác nhận yêu cầu để làm rõ ràng buộc hệ thống và mức ảnh hưởng của từng phương án, rồi chỉ chốt khi có sự chấp thuận của các bên liên quan. [Cần bổ sung: ví dụ thật.]"],
      ["Kể về lần bạn phải từ chối hoặc đẩy lùi yêu cầu của stakeholder",
        "Không có ví dụ trong CV",
        "[Cần bổ sung: ví dụ thật.] Khung: nêu ràng buộc và mức ảnh hưởng theo business impact và urgency, đề xuất phương án thay thế trong giới hạn hệ thống."],
      ["Yêu cầu mơ hồ từ business thì bạn làm gì?",
        "Khảo sát, phân tích hiện trạng, đề xuất giải pháp",
        "Em khảo sát và làm rõ với stakeholder, phân tích hiện trạng nền tảng để chẩn đoán vấn đề, đề xuất giải pháp rồi xác nhận lại trước khi viết PRD. [Cần bổ sung: một ví dụ thật.]"],
      ["Bạn làm việc với khách hàng nội bộ và đối tác bên ngoài khác nhau thế nào?",
        "Đội client (VNShop), NCC, đối tác vận chuyển, IT nội bộ",
        "Với đội client em khảo sát và chốt phạm vi qua Fit-Gap. Với đối tác (NCC, vận chuyển) em làm việc qua Open API và tài liệu hướng dẫn. Với IT em làm qua PRD và backlog."],
      ["Bạn trình bày PRD cho stakeholder và dev thế nào?",
        "Present để align scope và execution",
        "Em trình bày PRD/BRD và User Story cho stakeholder và đội dev để thống nhất phạm vi và cách thực hiện trước khi triển khai. [Cần bổ sung: cách bạn điều chỉnh nội dung cho từng nhóm người nghe.]"],
      ["Bạn làm market research và competitor benchmarking ra sao?",
        "Kỹ năng trong CV: benchmark đối thủ, xu hướng thị trường, gap tính năng/UX",
        "[Cần bổ sung: một ví dụ cụ thể, ví dụ hotel booking hoặc ticketing.] JD cũng yêu cầu phân tích thị trường cho cash loan và BNPL, nên chuẩn bị thêm cách bạn sẽ nghiên cứu mảng này."],
      ["Bạn đào tạo vận hành và nhân sự tuyến đầu thế nào khi ra feature mới?",
        "Tài liệu và training cho đội vận hành, kho, nhà cung cấp",
        "Với mỗi tính năng mới em viết tài liệu và tổ chức training nội bộ cho vận hành, kho và nhà cung cấp để nhân sự tuyến đầu hiểu rõ sản phẩm trước khi dùng. [Cần bổ sung: một tính năng cụ thể và phản hồi nhận được.]"],
    ]],
    ["D. Đối tác bên ngoài và tích hợp", [
      ["Kể về dự án bạn co-develop hoặc tích hợp với đối tác",
        "Open API cho NCC: đồng bộ tồn kho, trạng thái kiện, bàn giao vận chuyển, huỷ/hoàn",
        "Em thiết kế Open API cho nhà cung cấp gồm đồng bộ tồn kho, cập nhật trạng thái kiện, bàn giao vận chuyển và huỷ/hoàn, nhằm số hoá quy trình vận hành và giảm phụ thuộc vào thao tác thủ công. [Cần bổ sung: vai trò của đối tác trong quá trình đồng phát triển, ai làm gì, kết quả.]"],
      ["Bạn thiết kế API spec cho đối tác thế nào?",
        "Open API specification",
        "Em viết đặc tả API cho bốn nhóm nghiệp vụ trên. [Cần bổ sung từ tài liệu Open API của bạn: cơ chế xác thực, webhook hay polling, xử lý lỗi.]"],
      ["Đối tác không đáp ứng timeline hoặc spec, bạn xử lý ra sao?",
        "Không có ví dụ trong CV",
        "[Cần bổ sung: ví dụ thật.] Khung: làm rõ nguyên nhân, chia nhỏ phạm vi theo timeline go-live, thống nhất phương án với các bên liên quan."],
      ["Bạn onboard đối tác mới thế nào?",
        "Tài liệu và training cho đội supplier",
        "Em xây tài liệu và training cho đội nhà cung cấp khi ra tính năng mới. [Cần bổ sung: các bước onboard NCC vào Open API, ví dụ môi trường thử, checklist.]"],
      ["Bạn xử lý lỗi và đồng bộ dữ liệu giữa hai hệ thống ra sao?",
        "Đồng bộ tồn kho, trạng thái kiện; TOSY: data integrity, migration, Tier 3",
        "Open API của em phủ đồng bộ tồn kho và cập nhật trạng thái kiện. Ở TOSY em chịu trách nhiệm toàn vẹn dữ liệu và migration hệ thống, và làm việc với Microsoft Support (Lifecycle Services) để xử lý sự cố production Tier 3. [Cần bổ sung: cách bạn phát hiện và xử lý sai lệch giữa hai hệ thống.]"],
    ]],
    ["E. Lending domain", [
      ["Phân biệt cash loan, personal loan, installment loan, line of credit, BNPL",
        "Nói rõ bạn đang học mảng này",
        "Cash loan/personal loan: vay tiền một lần, số tiền và kỳ hạn cố định, trả định kỳ. Installment loan: trả góp theo lịch cố định, thường gắn với mục đích cụ thể. Line of credit: hạn mức xoay vòng, dùng và trả nhiều lần, lãi tính trên dư nợ. BNPL: mua trước trả sau tại điểm bán, kỳ ngắn, hạn mức nhỏ."],
      ["Mô tả luồng loan origination từ đăng ký đến giải ngân",
        "Không có trong CV",
        "Thu thập thông tin khách hàng, xác thực danh tính, thẩm định và chấm điểm tín dụng, quyết định duyệt và hạn mức, ký hợp đồng, giải ngân. [Cần bổ sung: bước nào là nơi sản phẩm công ty này khác biệt, sau khi bạn tìm hiểu.]"],
      ["Underwriting là gì? Dữ liệu nào dùng để chấm điểm?",
        "Không có trong CV",
        "Underwriting là đánh giá khả năng và ý thức trả nợ để quyết định duyệt, hạn mức và lãi suất. Dữ liệu thường dùng: thông tin khách hàng khai báo, thu nhập, lịch sử tín dụng (ví dụ từ CIC), dữ liệu hành vi và giao dịch."],
      ["Loan servicing lifecycle gồm những gì?",
        "Không có trong CV",
        "Nhắc lịch thanh toán, ghi nhận thanh toán, xử lý trả chậm, thu hồi nợ (collection), tất toán hoặc trả trước hạn, hỗ trợ khách hàng, báo cáo."],
      ["Các chỉ số của sản phẩm cho vay: approval rate, NPL, DPD, vintage, roll rate",
        "Không có trong CV",
        "Approval rate: tỷ lệ hồ sơ được duyệt. DPD: số ngày quá hạn. NPL: tỷ lệ nợ xấu. Roll rate: tỷ lệ khoản vay chuyển sang nhóm quá hạn nặng hơn. Vintage: chất lượng danh mục theo tháng giải ngân. Thêm conversion và collection rate."],
      ["BNPL khác cho vay tiền mặt về rủi ro và mô hình doanh thu ra sao?",
        "Không có trong CV",
        "BNPL gắn với giao dịch mua tại merchant, hạn mức nhỏ, kỳ ngắn, quyết định ngay khi thanh toán. Cho vay tiền mặt giải ngân tiền cho khách, hạn mức và kỳ hạn lớn hơn, nên rủi ro và chi phí thu nợ khác nhau. Doanh thu BNPL thường có phí từ merchant; cho vay tiền mặt chủ yếu từ lãi và phí. [Cần bổ sung: kiểm chứng theo mô hình của công ty phỏng vấn.]"],
      ["Bạn sẽ thiết kế một sản phẩm BNPL mới từ đầu thế nào?",
        "Dùng quy trình đã làm: khảo sát, Fit-Gap, đối tác, đo lường",
        "Em bắt đầu bằng khảo sát nhu cầu và phân tích thị trường, xác nhận Fit-Gap với nền tảng hiện có, chọn MVP nhỏ, đồng thiết kế tích hợp với đối tác như em đã làm với Open API, làm việc với Risk, Legal, Compliance về điều kiện duyệt và tuân thủ, rồi cùng Data đặt dashboard theo dõi."],
      ["Bạn hiểu gì về quy định cho vay và tài chính tiêu dùng tại VN?",
        "Không có trong CV",
        "[Cần bổ sung: tự tra cứu và chỉ nêu văn bản bạn đã đọc.] Chủ đề nên tra: cho vay tiêu dùng, phân loại nợ và trích lập dự phòng, bảo vệ dữ liệu cá nhân, xác thực khách hàng điện tử. Nếu chưa chắc, nói rõ em đang tìm hiểu và sẽ xác nhận cùng Legal, Compliance."],
      ["Bạn biết gì về fintech và lending ở VN?",
        "Không có trong CV",
        "[Cần bổ sung: nghiên cứu công ty phỏng vấn và đối thủ; nêu 2-3 sản phẩm bạn đã dùng thử và so sánh.]"],
      ["Bạn có kinh nghiệm gì với ngân hàng hoặc tổ chức tài chính?",
        "Chỉ có VNPAY (thanh toán), AP/AR ở TOSY",
        "Em chưa làm tại ngân hàng hoặc tổ chức cho vay. Em có kinh nghiệm sản phẩm fintech ở VNPAY và số hoá quy trình tài chính (AP/AR) trên D365 F&O ở TOSY."],
    ]],
    ["F. Risk và Compliance", [
      ["Bạn làm việc với Risk, Legal, Compliance thế nào khi ra sản phẩm?",
        "CV chưa có ví dụ trực tiếp",
        "[Cần bổ sung: ví dụ thật, ví dụ chính sách, phân quyền, quy trình phê duyệt ở VNShop hoặc VNPAY.] Nếu chưa có, nói thẳng và trình bày cách làm em đã dùng: xác nhận yêu cầu và xin chấp thuận của tất cả bên liên quan."],
      ["Khi yêu cầu business mâu thuẫn với compliance, bạn xử lý ra sao?",
        "Quy trình align và get approval từ tất cả stakeholder",
        "Em đưa cả hai bên vào cùng một phiên xác nhận, làm rõ ràng buộc và ảnh hưởng, đề xuất phương án đáp ứng được yêu cầu tuân thủ trước, và chỉ chốt khi các bên liên quan đồng ý. [Cần bổ sung: ví dụ thật nếu có.]"],
      ["Làm sao đảm bảo tính toàn vẹn dữ liệu và audit trail?",
        "TOSY: data integrity, migration; Tier 3 với Microsoft Support",
        "Ở TOSY em chịu trách nhiệm toàn vẹn dữ liệu doanh nghiệp và migration hệ thống, và xử lý sự cố production Tier 3 cùng Microsoft Support. [Cần bổ sung: cách bạn đảm bảo audit trail cụ thể, nếu có.]"],
      ["Bạn cân bằng tăng trưởng (approval rate) với kiểm soát rủi ro thế nào?",
        "Không có trong CV",
        "[Cần bổ sung: quan điểm của bạn.] Khung: duyệt nhiều hơn làm tăng doanh thu nhưng có thể làm tăng nợ xấu, nên PO cùng Risk và Data đặt ngưỡng, theo dõi cả approval rate lẫn chỉ số chất lượng danh mục (NPL, DPD) và điều chỉnh dần."],
      ["Bạn xử lý chính sách và quy trình sản phẩm (product policies) ra sao?",
        "\"Product policies/processes\" trong Skills",
        "Em xây dựng chính sách và quy trình sản phẩm rồi đưa vào tài liệu PRD/BRD và training cho vận hành. [Cần bổ sung: một chính sách cụ thể bạn đã viết.]"],
    ]],
    ["G. Data-driven", [
      ["Bạn làm việc với Data Analyst để xây dashboard thế nào?",
        "Power BI dashboard real-time cho management (TOSY)",
        "Ở TOSY em xây dashboard Power BI tự động để ban quản lý xem số liệu vận hành theo thời gian thực. [Cần bổ sung: cách bạn phối hợp với DA ở VNPAY, ví dụ xác định chỉ số, yêu cầu báo cáo.]"],
      ["Bạn dùng dữ liệu để phát hiện vấn đề và nhu cầu khách hàng ra sao?",
        "Phân tích hiện trạng nền tảng, chẩn đoán vấn đề vận hành",
        "Em phân tích hiện trạng nền tảng để chẩn đoán vấn đề vận hành rồi đề xuất giải pháp; ở TOSY em có dashboard Power BI cho quản lý. [Cần bổ sung: một ví dụ từ dữ liệu ra insight ra quyết định.]"],
      ["Bạn có dùng SQL không? Mức độ?",
        "CV có Power BI; không ghi SQL, Tableau hay Excel",
        "[Cần bổ sung: trả lời đúng thực tế.] JD ghi SQL, Tableau là điểm cộng, không phải bắt buộc. Nếu chưa dùng thực tế, nói thẳng và nêu kế hoạch học cụ thể, kèm Power BI bạn đã làm."],
      ["Chọn KPI nào để theo dõi sản phẩm cho vay?",
        "Không có trong CV",
        "[Cần bổ sung: chọn 3-5 KPI và giải thích vì sao.] Gợi ý: conversion, approval rate, tỷ lệ giải ngân, DPD, NPL, collection rate."],
      ["Kể về quyết định sản phẩm bạn đưa ra nhờ dữ liệu",
        "Auto-assign carrier (hàng nghìn đơn mỗi ngày, vài phút)",
        "Có thể dùng luồng auto-assign carrier: xử lý hàng nghìn đơn mỗi ngày từ thủ công xuống còn vài phút. [Cần bổ sung: dữ liệu bạn đã dùng để quyết định, số liệu trước và sau.]"],
      ["Bạn thiết kế A/B test hoặc đánh giá hiệu quả thế nào?",
        "Không có trong CV",
        "[Cần bổ sung: ví dụ thật.] Nếu chưa có, nói cách bạn sẽ đánh giá: đặt metric và mốc so sánh trước và sau, theo dõi cùng DA."],
    ]],
    ["H. Tình huống và behavioral", [
      ["Kể về dự án khó nhất và cách bạn vượt qua",
        "Open API hoặc auto-assign carrier",
        "Chọn một trong hai. Open API: em thiết kế đặc tả cho bốn luồng (tồn kho, trạng thái kiện, bàn giao vận chuyển, huỷ/hoàn). Auto-assign: rule theo kho, xử lý hàng nghìn đơn từ thủ công xuống vài phút. [Cần bổ sung theo STAR: khó khăn cụ thể, hành động của bạn, kết quả.]"],
      ["Kể về một quyết định sai và bài học",
        "Không có trong CV",
        "[Cần bổ sung: ví dụ thật.] Nên chọn một sai lầm thật, nói rõ hậu quả và điều bạn đã thay đổi."],
      ["Bạn làm gì khi go-live gặp sự cố?",
        "Go-live coordination; Tier 3 ở TOSY",
        "Em điều phối IT, vận hành và đối tác đến go-live; ở TOSY em cùng Microsoft Support xử lý sự cố production Tier 3. [Cần bổ sung: một sự cố cụ thể và cách xử lý.]"],
      ["Bạn xử lý áp lực deadline và nhiều đầu việc song song thế nào?",
        "Điều phối IT, vận hành, đối tác theo go-live",
        "Em xếp backlog theo business impact và urgency, giao việc cho IT, vận hành, đối tác để giữ tiến độ đến go-live. [Cần bổ sung: ví dụ thật.]"],
      ["Bạn học một lĩnh vực mới nhanh ra sao?",
        "ERP sang fintech; AI agent, Knowledge Graph, Power Platform",
        "Em chuyển từ ERP (D365 F&O, Power Platform) sang sản phẩm fintech, và tự xây Knowledge Graph cùng 2 AI agent skill để học và tra cứu nghiệp vụ nhanh hơn. [Cần bổ sung: cách bạn đang học lending cụ thể.]"],
      ["Bạn dùng AI trong công việc BA thế nào?",
        "Knowledge Graph + 2 AI agent skills trên Claude",
        "Em xây Knowledge Graph cho VnShop và D365 F&O, cùng 2 AI agent skill trên Claude để tra cứu định nghĩa nghiệp vụ và phân tích tác động khi tài liệu SRS/URD thay đổi. Thời gian phân tích tác động khi chuẩn bị PRD giảm từ vài giờ xuống dưới 15 phút, và giảm rủi ro bỏ sót module liên quan. Nên chuẩn bị thêm câu trả lời về bảo mật dữ liệu khi dùng AI, vì công ty tài chính thường hỏi điều này."],
      ["Kể về lần bạn thuyết phục được người không đồng ý",
        "Không có trong CV",
        "[Cần bổ sung: ví dụ thật.] Khung: dựa trên dữ liệu, mức ảnh hưởng và kết quả Fit-Gap đã xác nhận."],
      ["Mức lương mong muốn và thời gian nhận việc?",
        "Không có trong CV",
        "[Cần bổ sung: câu trả lời của bạn.]"],
    ]],
    // Group I: the third column in Notion is "purpose" and the fourth is "what to listen for".
    ["I. Câu hỏi hỏi lại phỏng vấn viên", [
      ["Sản phẩm PO này phụ trách hiện ở giai đoạn nào (mới, tăng trưởng, tối ưu)?",
        "Mục đích: hiểu phạm vi",
        "Nên lắng nghe: PO có quyền quyết định roadmap hay chỉ thực thi"],
      ["Team có bao nhiêu dev, DA, và PO phối hợp với Risk/Compliance thế nào?",
        "Mục đích: cơ cấu và cách phối hợp",
        "Nên lắng nghe: có nhóm Risk riêng làm việc cùng PO không, tần suất phối hợp"],
      ["Đối tác bên ngoài chính là ai (bank, credit bureau, merchant...)?",
        "Mục đích: hiểu mô hình",
        "Nên lắng nghe: mức độ tích hợp PO phải làm, để nối với kinh nghiệm Open API"],
      ["Chỉ số nào quyết định thành công của vị trí này trong 6-12 tháng đầu?",
        "Mục đích: kỳ vọng",
        "Nên lắng nghe: KPI cụ thể để đối chiếu với năng lực bạn có"],
      ["Roadmap hiện tại và thách thức lớn nhất của sản phẩm là gì?",
        "Mục đích: bối cảnh",
        "Nên lắng nghe: rủi ro lớn nhất và việc bạn sẽ phải xử lý trước"],
      ["Công ty dùng stack dữ liệu nào (SQL, Tableau...)? PO có tự truy vấn không?",
        "Mục đích: làm rõ gap dữ liệu",
        "Nên lắng nghe: PO cần tự viết SQL hay chỉ làm việc với DA, để đánh giá mức độ gap của bạn"],
      ["Có chương trình đào tạo domain lending cho người mới không?",
        "Mục đích: bù gap có chủ đích",
        "Nên lắng nghe: mức hỗ trợ người chưa có kinh nghiệm lending"],
      ["Quy trình ra quyết định giữa Product, Risk và Business diễn ra thế nào?",
        "Mục đích: văn hoá phối hợp",
        "Nên lắng nghe: ai quyết định cuối cùng khi có xung đột, tốc độ phê duyệt"],
      ["Tại sao vị trí này đang mở?",
        "Mục đích: bối cảnh tuyển dụng",
        "Nên lắng nghe: mở mới do mở rộng hay thay người, và lý do"],
      ["Bước tiếp theo trong quy trình tuyển dụng là gì?",
        "Mục đích: kết thúc phỏng vấn",
        "Nên lắng nghe: số vòng còn lại và mốc thời gian"],
    ]],
    ["J. Giới thiệu sản phẩm VNShop & USP (Product Sense)", [
      ["Giới thiệu tổng quan về sản phẩm VNShop mà bạn đang làm, với vai trò một PO",
        "VNShop là nền tảng thương mại điện tử nằm trong hệ sinh thái app/ví điện tử VNPAY; bạn phụ trách Back Office quản lý đơn hàng, tồn kho, nhà cung cấp",
        "VNShop là sản phẩm thương mại điện tử tích hợp trong hệ sinh thái app/ví điện tử của VNPAY, cho phép người dùng mua hàng từ nhiều nhà cung cấp (NCC) ngay trong app họ đã dùng để thanh toán. Em phụ trách phần Back Office (BO) — hệ thống kiểu ERP tự xây dựng, xử lý đơn hàng, tồn kho và vận hành với NCC, giúp đội vận hành và kho xử lý hàng nghìn đơn mỗi ngày. [Cần bổ sung: quy mô hiện tại (số NCC, số đơn/tháng nếu được phép nói) để câu trả lời cụ thể hơn.]"],
      ["Unique Selling Point của sản phẩm là gì?",
        "Chưa ghi rõ trong CV/hồ sơ — cần bạn xác nhận",
        "[Cần bổ sung: USP thật theo góc nhìn của bạn.] Hướng gợi ý để bạn đối chiếu: (1) mua hàng ngay trong app thanh toán đã có sẵn lượng người dùng lớn, không cần cài thêm app; (2) vận hành backend tự động hoá (ví dụ auto-assign carrier) giúp xử lý đơn nhanh hơn đối thủ; (3) tích hợp thanh toán sẵn có, giảm ma sát lúc trả tiền so với sàn thương mại điện tử độc lập. Nên chọn đúng 1 USP thật sự đúng, không nói cả ba nếu chưa kiểm chứng."],
      ["Ai là người dùng chính, họ dùng sản phẩm để giải quyết vấn đề gì?",
        "BO phục vụ đội vận hành/kho/NCC; người mua dùng qua app VNPAY",
        "Có hai nhóm người dùng: người mua hàng qua app VNPAY, và đội vận hành/kho/NCC dùng Back Office để xử lý đơn, tồn kho, giao hàng. Em tập trung giải quyết vấn đề cho nhóm thứ hai: giảm thao tác thủ công, tránh sai sót khi đơn tăng nhanh."],
      ["Vì sao khách hàng chọn VNShop thay vì kênh khác?",
        "Không có trong CV",
        "[Cần bổ sung: câu trả lời thật, lý tưởng là có dữ liệu hoặc phản hồi khách hàng hỗ trợ.] Nếu chưa có số liệu, nên trả lời theo hướng giả thuyết và nói rõ đây là giả thuyết chưa kiểm chứng bằng dữ liệu, để tránh bị bắt bẻ."],
    ]],
    ["K. Cơ cấu team & cách PO vận hành (Execution)", [
      ["Mô tả cơ cấu team bạn đang làm việc cùng (dev, DA, QA, design...)",
        "Không ghi cụ thể số lượng trong CV",
        "[Cần bổ sung: số lượng dev/QA/DA, bạn báo cáo cho ai.] Khung trả lời: nêu rõ các vai trò (IT, vận hành, kho, NCC, đối tác) và vai trò PO là điều phối giữa các bên này đến go-live, giống như CV đã mô tả."],
      ["Team PO được tổ chức và vận hành ra sao (bạn báo cáo cho ai, phối hợp với ai hàng ngày)?",
        "Điều phối IT, vận hành, đối tác đến go-live",
        "Em làm cầu nối giữa đội client VNShop, IT, vận hành/kho và đối tác để giữ tiến độ đến go-live. [Cần bổ sung: cấp quản lý trực tiếp của bạn, tần suất họp với từng nhóm.]"],
      ["Một ngày làm việc điển hình của bạn là gì?",
        "Không có trong CV",
        "[Cần bổ sung: miêu tả thật.] Nên nêu theo trình tự thật: kiểm tra backlog/ticket, làm việc với stakeholder hoặc dev, viết tài liệu, theo dõi go-live — tránh liệt kê chung chung."],
      ["Quy trình từ ý tưởng đến go-live tại VNShop diễn ra thế nào, ai tham gia từng bước?",
        "Khảo sát → Fit-Gap → PRD/BRD → backlog → triển khai → training → đánh giá sau go-live",
        "Em bắt đầu bằng khảo sát stakeholder và xác nhận Fit-Gap, viết PRD/BRD và trình bày cho stakeholder và dev, ưu tiên backlog theo impact/urgency, điều phối IT/vận hành/đối tác đến go-live, rồi đào tạo vận hành và đánh giá sau launch. [Cần bổ sung: thời gian trung bình mỗi bước nếu được hỏi sâu hơn.]"],
    ]],
  ];

  const out = [];
  groups.forEach(([category, items]) => {
    items.forEach(([question, hint, draft]) => {
      out.push({ id: "q" + (out.length + 1), category, question, hint, draft });
    });
  });
  window.SEED_QUESTIONS = out;
})();
